[package]
name = "gtk4-rs-examples"
version = "0.1.0"
authors = ["wangjun <wangjun@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
